[package]
name = "parqour"
version = "0.1.0"
edition = "2021"

[dependencies]
arrow = { version = "52.0.0", default-features = false }
clap = { version = "4.5.7", features = ["derive"] }
crossterm = "0.27.0"
parquet = "52.0.0"
ratatui = "0.26.3"
serde = { version = "1.0.203", features = ["derive"] }
